<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
		<CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
	</PropertyGroup>

	<ItemGroup>
		<PackageVersion Include="Auth0.AspNetCore.Authentication" Version="1.11.0" />
		<PackageVersion Include="DotNetEnv" Version="3.2.0" />
		<PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12" />
		<PackageVersion Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.12" />
		<PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
	</ItemGroup>
</Project>
