// <auto-generated />
using System;
using AtelierStore.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AtelierStore.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260927032014_SlugLowercaseConstraints")]
    partial class SlugLowercaseConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AtelierStore.Web.Data.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_slug");

                    b.ToTable("categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_categories_slug_lowercase", "slug = lower(slug)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Outerwear",
                            Slug = "outerwear"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Knitwear",
                            Slug = "knitwear"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Trousers",
                            Slug = "trousers"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Handbags",
                            Slug = "handbags"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Shoes",
                            Slug = "shoes"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Eyewear",
                            Slug = "eyewear"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Jewelry",
                            Slug = "jewelry"
                        });
                });

            modelBuilder.Entity("AtelierStore.Web.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Badge")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("badge");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("image_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<decimal?>("WasPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("was_price");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_products_slug");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_price_non_negative", "price >= 0");

                            t.HasCheckConstraint("ck_products_slug_lowercase", "slug = lower(slug)");

                            t.HasCheckConstraint("ck_products_was_price_above_price", "was_price IS NULL OR was_price > price");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Badge = "New",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Cut from supple lambskin with a slightly cropped body, asymmetric zip and quilted shoulders. Lined in cupro, so it layers easily over knitwear.",
                            ImageId = "1551028719-00167b16eac5",
                            Name = "Leather Biker Jacket",
                            Price = 2400m,
                            Slug = "leather-biker-jacket"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Knitted by hand in a soft wool and alpaca blend, finished with a long fringed hem. Drapes loosely from the shoulders and wears over coats or alone.",
                            ImageId = "1434389677669-e08b4cac3105",
                            Name = "Hand-Knit Fringe Poncho",
                            Price = 980m,
                            Slug = "hand-knit-poncho"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Washed silk twill with a drawstring waist and cuffed ankles. Relaxed through the leg, with deep side pockets and a fluid, matte finish.",
                            ImageId = "1594633312681-425c7b97ccd1",
                            Name = "Silk Jogger Trouser",
                            Price = 540m,
                            Slug = "silk-jogger",
                            WasPrice = 720m
                        },
                        new
                        {
                            Id = 4,
                            Badge = "Exclusive",
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A structured calfskin bag with a rolled top handle, detachable shoulder strap and palladium hardware. The interior is lined in suede, with one zip pocket.",
                            ImageId = "1584917865442-de89df76afd3",
                            Name = "Structured Top-Handle Bag",
                            Price = 2950m,
                            Slug = "top-handle-bag"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "An open canvas tote printed with an archive botanical motif and trimmed in vegetable-tanned leather. Roomy enough for a laptop and a day's essentials.",
                            ImageId = "1591561954557-26941169b49e",
                            Name = "Botanical Print Tote",
                            Price = 1850m,
                            Slug = "botanical-tote"
                        },
                        new
                        {
                            Id = 6,
                            Badge = "New",
                            CategoryId = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A retro runner built from suede and technical mesh panels on a lightweight rubber sole. Made in Italy and finished with a padded collar.",
                            ImageId = "1560769629-975ec94e6a86",
                            Name = "Panelled Runner Sneaker",
                            Price = 790m,
                            Slug = "panelled-runner-sneaker"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Fine round frames in brushed gold-tone metal with adjustable nose pads and tinted lenses offering full UV protection. Comes with a leather case.",
                            ImageId = "1511499767150-a48a237f0083",
                            Name = "Round Metal Sunglasses",
                            Price = 390m,
                            Slug = "round-metal-sunglasses"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Freshwater pearls, hand-knotted on silk and closed with an engraved gold vermeil clasp. Sits close at the base of the neck.",
                            ImageId = "1515562141207-7a88fb7ce338",
                            Name = "Pearl Collar Necklace",
                            Price = 1450m,
                            Slug = "pearl-collar-necklace"
                        });
                });

            modelBuilder.Entity("AtelierStore.Web.Data.ProductStock", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ProductId")
                        .HasName("pk_product_stock");

                    b.ToTable("product_stock", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_stock_quantity_non_negative", "quantity >= 0");
                        });

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Quantity = 6,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ProductId = 2,
                            Quantity = 2,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ProductId = 3,
                            Quantity = 9,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ProductId = 4,
                            Quantity = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ProductId = 5,
                            Quantity = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ProductId = 6,
                            Quantity = 12,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ProductId = 7,
                            Quantity = 7,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ProductId = 8,
                            Quantity = 3,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AtelierStore.Web.Data.Product", b =>
                {
                    b.HasOne("AtelierStore.Web.Data.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AtelierStore.Web.Data.ProductStock", b =>
                {
                    b.HasOne("AtelierStore.Web.Data.Product", "Product")
                        .WithOne("Stock")
                        .HasForeignKey("AtelierStore.Web.Data.ProductStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_stock_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AtelierStore.Web.Data.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AtelierStore.Web.Data.Product", b =>
                {
                    b.Navigation("Stock")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
