<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
		<PackageReference Include="Respawn" />
		<PackageReference Include="Testcontainers.PostgreSql" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\AtelierStore.Web\AtelierStore.Web.csproj" />
	</ItemGroup>

</Project>
